### PR TITLE
Fix inappropriate capitalisation

### LINKED ISSUE #159: Inappropriate capitalisation in feed status UI / feed UI copy review
### Describe the bug:
Noticed when looking at screenshot from #155:

129411352-7a846d82-961e-4e38-862d-421d54aebc9b

- `Product feed configured for Ingestion on Pinterest` has `Ingestion` capitalised. 
- Should be `Product feed configured for ingestion on Pinterest`.

When fixing this let's review all these strings to make sure there are no other errors and that this UI is as clear and helpful as possible. Ideally we can combine this with a flowchart/support doc of the steps to successful sync (#132)

### Steps to reproduce:
TBC - onboard and enable product sync.

(I'm having issues with product sync right now so can't actually reproduce this exact error in the UI.)

### PR DESCRIPTION
**Pull request by ecgan**
Closes #159. 

### Changes proposed in this pull request

This PR fixes a number of text capitalisation issues as described in #159. I generated the `.pot` file, manually scan all the texts in the file, and fix the original texts in the code base. See the list of commits for each piece of text that I fixed.

### Changelog note

> Fix: text capitalisation issues.

### CODE REVIEW

File: assets/source/setup-guide/app/steps/SetupAccount.js [hunk 1]
```diff
@@ -62,7 +62,7 @@ const SetupAccount = ( {
 				'error',
 				error.message ||
 					__(
-						'Couldn’t retrieve your Linked Business Accounts.',
+						'Couldn’t retrieve your linked business accounts.',
```
Comment (ecgan) [inline assets/source/setup-guide/app/steps/SetupAccount.js:65]: The phrase "linked business accounts" and its capitalisation is based on what I found here: https://help.pinterest.com/en/business/article/get-a-business-account.

**Review by JPry — APPROVED** [review]
LGTM 🚀
