### PR TITLE
Fix products with 'on backorder' status are skipped from a feed.

### LINKED ISSUE #717: Include Backordered items in feed file
### Describe the bug:

When "Hide out of stock items from the catalog" is checked in WooCommerce Settings, only in stock items are synced to the Pinterest feed. This prevents back ordered items that would usually be visible in the catalog from being sent to Pinterest. 

This was changed in #284 

### Steps to reproduce:

1. Have products with out of stock and backorder status and check Hide out of stock items from the catalog
2. Only the in stock items are added to the generated feed
3. Uncheck Hide out of stock items from the catalog and force feed regeneration from scheduled actions
4. All products appear in the feed

### Expected behavior:

Since back ordered items appear in the WooCommerce catalog and are not hidden, I would expect them to be added to the Pinterest feed. 

### Actual behavior:

As the feed generator only looks for the `instock` status, the `preorder` status is skipped. https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/FeedGenerator.php#L289
We map backordered WooCommerce products to the Pinterest `preorder` status in status here: https://github.com/woocommerce/pinterest-for-woocommerce/blob/b5076f0fb399eb5ba156813b1a6ee71f469f9d79/src/ProductsXmlFeed.php#L354

### Additional details:

Reported in 6058102-zen

### PR DESCRIPTION
**Pull request by message-dimke**
### Changes proposed in this Pull Request:

Closes #717 .

It was reported products with status of 'On backorder' were not included into a Pinterest feed file. Current PR fixes this bug.

### Detailed test instructions:

1. Make sure you have `Hide out of stock items from the catalog` enabled.

WooCommerce_settings_‹_WordPress_Pinterest_—_WordPress

2. Make sure you have at least a single product with Stock Status set to `On backorder`.

Edit_product_“Simple_product”_‹_WordPress_Pinterest_—_WordPress

AND/OR

Edit_product_“Simple_product__updated_”_‹_WordPress_Pinterest_—_WordPress

**NOTE!** _Both variants must be tested._

3. When on `develop` branch run `pinterest-for-woocommerce-start-feed-generation` action from `Pending` tab.

WooCommerce_status_‹_WordPress_Pinterest_—_WordPress

4. Check the feed file by following the link to the feed file. 

Products_Catalog_‹_Pinterest_‹_Marketing_‹_WooCommerce_‹_WordPress_Pinterest_—_WooCommerce

5. Find no products with Stock Status `On backorder`. Such products would appear in the feed with `<g:availability>preorder</g:availability>` tag. E.g.

https___pinterest_dima_works_wp-content_uploads_pinterest-for-woocommerce-sLGSPc_xml

6. Checkout `fix/717-onbackorder-products-arent-included-into-a-feed`  branch.
7. Run `pinterest-for-woocommerce-start-feed-generation` again.
8. Check the feed file.
9. See  the feed now includes products with Stock Status set `On backorder` (but in the feed it is transformed into `preorder`).

### Changelog entry

> Fix - On backorder items missing from the feed.

### CODE REVIEW

**Review by budzanowski — CHANGES_REQUESTED** [review]
This looks great. Please just add `@since` param to the methods https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#since-section-changelogs

File: tests/Unit/FeedGeneratorTest.php [hunk 1]
```diff
@@ -286,4 +286,45 @@ public function test_handle_batch_action_retries_up_to_two_times_on_timeout() {
 
 		$this->assertEquals( 'error', ProductFeedStatus::get()['status'] );
 	}
+
+	/**
+	 * Tests get feed products method returns products in stock including products on backorder.
+	 *
+	 * @return void
+	 */
+	public function test_get_feed_products_return_backorder_enabled_products() {
```
Comment (budzanowski) [inline tests/Unit/FeedGeneratorTest.php:295]: Awesome job with the test.

**Review by budzanowski — APPROVED** [review]
:shipit:
