### PR TITLE
Fix typo errors on translatable strings

### LINKED ISSUE #478: Strings with typos
# Describe the bug:

There are some translatable strings within the extension that have typos e.g. 

> Visit the <a href="{...}">settings</a> page to enabled it.`

it should be "enable"

> Last activity: %1$s ago - Wrote %2$s products to %3$sfeed file%4$s.

The string must be plural

# Steps to reproduce:

View https://github.com/woocommerce/pinterest-for-woocommerce/blob/77a44f3e1f08e43a8c1b6d9858d89a21500d11fc/src/API/FeedState.php#L119 or within the extension for context

# Expected behavior:

No typos

# Actual behavior:

There are typos

# Additional details:

Suggest reviewing other text for any simple fixes - any doubt please confirm with product team

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Changes proposed in this Pull Request:

Closes #478.

Fix typo errors on translatable strings:
- 'If you have a valid reason (such as having corrected the violations that resulted in the dissaproval)' --> 'If you have a valid reason (such as having corrected the violations that resulted in the disapproval)'
- 'You can check the the status of the generation process in the Catalog tab.' --> 'You can check the status of the generation process in the Catalog tab.'
- 'Please try agagin.' --> 'Please try again.'
- 'Visit the <a href="%1$s">settings</a> page to enabled it.' --> 'Visit the <a href="%1$s">settings</a> page to enable it.'
- Use of plurals on: 'Last activity: %1$s ago - Wrote %2$s product to %3$sfeed file%4$s.' and 'Successfully generated %1$s ago - Wrote %2$s product to %3$sfeed file%4$s'
- 'Response error when trying create a merchant or update the existing one.' --> 'Response error when trying to create a merchant or update the existing one.'

### Detailed test instructions:
1. Check the .pot translatable strings.
2. There should not be any typo errors.

### Changelog entry

> Fix - Typo errors on translatable strings.

### CODE REVIEW

**Review by sc-ecolasurdo — APPROVED** [review]

File: assets/source/setup-guide/app/components/HealthCheck/index.js [hunk 1]
```diff
@@ -167,7 +167,7 @@ const HealthCheck = () => {
 		pending_initial_configuration: {
 			status: 'warning',
 			message: __(
-				'The feed is being configured. Depending on the number of products this may take a while as the feed needs to be fully generated before its been sent to Pinterest for registration. You can check the the status of the generation process in the Catalog tab.',
+				'The feed is being configured. Depending on the number of products this may take a while as the feed needs to be fully generated before its been sent to Pinterest for registration. You can check the status of the generation process in the Catalog tab.',
```
Comment (JPry) [inline assets/source/setup-guide/app/components/HealthCheck/index.js]:
```suggestion
				'The feed is being configured. Depending on the number of products this may take a while as the feed needs to be fully generated before it is sent to Pinterest for registration. You can check the status of the generation process in the Catalog tab.',
```

File: assets/source/setup-guide/app/components/HealthCheck/index.js [hunk 2]
```diff
@@ -187,7 +187,7 @@ const HealthCheck = () => {
 				'pinterest-for-woocommerce'
 			),
 			body: __(
-				'If you have a valid reason (such as having corrected the violations that resulted in the dissaproval) for appealing a merchant review decision, you can submit an appeal.',
+				'If you have a valid reason (such as having corrected the violations that resulted in the disapproval) for appealing a merchant review decision, you can submit an appeal.',
```
Comment (JPry) [inline assets/source/setup-guide/app/components/HealthCheck/index.js]:
```suggestion
				'If you have a valid reason for appealing a merchant review decision (such as having corrected the violations that resulted in the disapproval), you can submit an appeal.',
```

File: src/API/FeedState.php [hunk 3]
```diff
@@ -186,8 +193,15 @@ private function add_local_feed_state( $result ) {
 				$status       = 'success';
 				$status_label = esc_html__( 'Up to date', 'pinterest-for-woocommerce' );
 				$extra_info   = sprintf(
-					/* Translators: %1$s Time string, %2$s total number of products */
-					esc_html__( 'Successfully generated %1$s ago - Wrote %2$s products to %3$sfeed file%4$s', 'pinterest-for-woocommerce' ),
+					esc_html(
+						/* Translators: %1$s Time string, %2$s total number of products */
```
Comment (JPry) [inline src/API/FeedState.php]: While we're editing this, we should also include 3 and 4 explanations in the translators comment.

Also, the word "translators" in the comment is supposed to be lowercased.

```suggestion
						/* translators: 1: Time string, 2: total number of products, 3: opening anchor tag, 4: closing anchor tag */
```

File: src/API/FeedState.php [hunk 4]
```diff
@@ -173,8 +173,15 @@ private function add_local_feed_state( $result ) {
 				$status       = 'pending';
 				$status_label = esc_html__( 'Feed generation in progress.', 'pinterest-for-woocommerce' );
 				$extra_info   = sprintf(
-					/* Translators: %1$s Time string, %2$s number of products */
-					esc_html__( 'Last activity: %1$s ago - Wrote %2$s products to %3$sfeed file%4$s.', 'pinterest-for-woocommerce' ),
+					esc_html(
+						/* Translators: %1$s Time string, %2$s number of products */
```
Comment (JPry) [inline src/API/FeedState.php]:
```suggestion
						/* translators: 1: Time string, 2: number of products, 3: opening anchor tag, 4: closing anchor tag */
```

**Review by JPry — CHANGES_REQUESTED** [review]

**Review by sc-ecolasurdo — APPROVED** [review]
