### PR TITLE
Back off mechanism for create merchant

### LINKED ISSUE #446: Investigate No relevant meta tag was found exception
Partner connect failed with exception "No relevant meta tag was found when creating merchant"

Over the last week a majority of errors came from
Domain ['https://scarfbank.com/gallery'] verification failed for user scarfbank
Domain ['https://www.bathroombutler.com/us'] verification failed for user bathroombutler

Below domains also had errors but number of errors were lower
Domain ['https://bathroombutdev.wpengine.com/us'] verification failed for user bathroombutler
Domain ['https://jorgephyttasraposo.com'] verification failed for user jaffrayhunter3426

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Changes proposed in this Pull Request:

Closes #446.

Follow up of the PR #512.
Implement progressive backing off of calling the merchant connect API.

### Additional details:
This adds a caching mechanism to requests made to the /catalogs/partner/connect/ endpoint. The cache starts off at 10 minutes, and then will double with every call to the API.

### Changelog entry

> Tweak - Backoff merchant creation in case of failure.

### CODE REVIEW

File: src/Merchants.php [hunk 1]
```diff
@@ -142,15 +142,36 @@ public static function update_or_create_merchant() {
 			'merchant_name'    => $merchant_name,
 		);
 
-		// The response only contains the merchant id.
-		$response = API\Base::update_or_create_merchant( $args );
+		$cache_key = PINTEREST_FOR_WOOCOMMERCE_PREFIX . '_request_' . md5( wp_json_encode( $args ) );
+		$cache     = get_transient( $cache_key );
+
+		if ( ! $cache ) {
```
Comment (budzanowski) [inline src/Merchants.php]: I think that this is wrong. If transient expires then `get_transient` will return `false` and we will get inside the `if` resulting in returned `false` value. We should use `get_transient` API directly and check for `false` explicitly:
```suggestion
		if ( false !== $cache ) {
```

Comment (alexiglesias31) [reply src/Merchants.php]: Of course :man_facepalming: 
Yes, that was the idea. Nice catch.

File: src/Merchants.php [hunk 2]
```diff
@@ -142,15 +142,36 @@ public static function update_or_create_merchant() {
 			'merchant_name'    => $merchant_name,
 		);
 
-		// The response only contains the merchant id.
-		$response = API\Base::update_or_create_merchant( $args );
+		$cache_key = PINTEREST_FOR_WOOCOMMERCE_PREFIX . '_request_' . md5( wp_json_encode( $args ) );
+		$cache     = get_transient( $cache_key );
+
+		if ( false !== $cache ) {
+			return $cache;
```
Comment (budzanowski) [inline src/Merchants.php]: If we have cache value then it means that we are delaying next fetch. We can't return something here because the rest of the code will expect a correct value. We need to throw an exception to signalise to the rest of the App what is going on. We should throw it with the original code and a message that this is a backoff attempt.

File: src/Merchants.php [hunk 3]
```diff
@@ -142,15 +142,36 @@ public static function update_or_create_merchant() {
...
+		}
+
+		try {
+			// The response only contains the merchant id.
+			$response = Base::update_or_create_merchant( $args );
+		} catch ( Throwable $th ) {
+			$delay = Pinterest_For_Woocommerce()::get_data( 'create_merchant_delay' ) ?? 10 * MINUTE_IN_SECONDS;
+
+			set_transient( $cache_key, $response, $delay );
```
Comment (budzanowski) [inline src/Merchants.php]: If there was an Exception then the `$response` is not defined. The only thing that we can store here is `$th->getCode`. We will be able to use it later in the cache check on line 149 for throwing an exception.

File: src/Merchants.php [hunk 4]
```diff
@@ -142,15 +142,36 @@ public static function update_or_create_merchant() {
...
+
+			// Double the delay.
+			Pinterest_For_Woocommerce()::save_data( 'create_merchant_delay', $delay * 2 );
```
Comment (budzanowski) [inline src/Merchants.php]: To prevent crazy values we should use max allowed value.
```suggestion
			Pinterest_For_Woocommerce()::save_data( 'create_merchant_delay', max( $delay * 2, HOUR_IN_SECONDS * 6 );
```

**Comment by alexiglesias31** [comment]
@budzanowski thanks for the feedback. Just updated the changes according to your comments.

File: src/Merchants.php [hunk 5]
```diff
@@ -142,15 +142,36 @@ public static function update_or_create_merchant() {
...
+
+		if ( false !== $cache ) {
+			throw new Exception( __( 'There was a previous error trying to create or update merchant.', 'pinterest-for-woocommerce' ), (int) $cache );
+		}
+
+		try {
+			// The response only contains the merchant id.
+			$response = Base::update_or_create_merchant( $args );
+		} catch ( Throwable $th ) {
+			$delay = Pinterest_For_Woocommerce()::get_data( 'create_merchant_delay' ) ?? 10 * MINUTE_IN_SECONDS;
```
Comment (budzanowski) [inline src/Merchants.php]: I did tested it and it works. Though I think that 10 minutes is much too aggressive. I have counted a multiple retries in a matter of couple of seconds when I have disabled the delay, if the first one would be just a fluke then the whole site would be blocked for the 10 minutes. I think that we can start with 1 minute. Getting to 10 is just 4 failed retries.

**Review by budzanowski — APPROVED** [review]
Left one comment but otherwise this is good to go.

**Comment by findingsimple** [comment]
@alexiglesias31 are your PR's / work still being reviewed/QA'd by a fellow sau/cal team member before getting to us?

I haven't seen anyone else around for a little bit or drafts.

**Comment by alexiglesias31** [comment]
Hi @jconroy,
We were opening directly the PRs on the tasks related to the Ads Credits flow (tested by me) and this one (follow up of a PR opened by Jpry).
We are moving back to the usual flow now.

File: src/Merchants.php (hunk 5 above)
Comment (alexiglesias31) [reply src/Merchants.php]: Done :white_check_mark:
