### PR TITLE
Move noscript code to the beginning of the body

### LINKED ISSUE #455: Invalid HTML in header
### Describe the bug:

> Hi, I have recently installed this plugin to sync products to Pinterest. Everything seemed to have gone ok until I checked our sitechecker software this morning (sitechecker.pro).
> It is now reporting a problem on every page of "Noscript in head contains invalid HTML elements". Apparently this can affect organic search and traffic. I've added a couple of links to the issue below:
> https://sitechecker.pro/site-audit-issues/noscript-head-contains-invalid-html-elements/
> https://sitebulb.com/hints/indexability/head-contains-invalid-html-elements/
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript
> 
> From what I have read the easiest option is to move the tag out of the head and into the body. Is there anyway to do this within the plugin?

WooCommerce.com Request Number: 252839

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Changes proposed in this Pull Request:

Closes #455  .

Move the `<noscript>` code to the beginning of the `<body>`.

### Screenshots:

pinterest-noscript

### Detailed test instructions:
1. Install the plugin and do the onboarding
2. Enable the tracking support.
3. The `<script` base code should be on the `<head>` and the `<noscript>` code at the beginning of the `<body>`

### Changelog entry

> Fix - Move the <noscript> base code to <body>

### CODE REVIEW

File: src/Tracking.php [hunk 1]
```diff
@@ -42,17 +42,26 @@ class Tracking {
...
+	 * Documentation: https://help.pinterest.com/en/business/article/install-the-pinterest-tag
+	 *
+	 * @var string
 	 */
-	private static $base_tag_em = "<script type=\"text/javascript\">\n  !function(e){if(!window.pintrk){window.pintrk=function(){window.pintrk.queue.push(Array.prototype.slice.call(arguments))};var n=window.pintrk;n.queue=[],n.version=\"3.0\";var t=document.createElement(\"script\");t.async=!0,t.src=e;var r=document.getElementsByTagName(\"script\")[0];r.parentNode.insertBefore(t,r)}}(\"https://s.pinimg.com/ct/core.js\");\n\n pintrk('load', '" . self::TAG_ID_SLUG . "', { em: '" . self::HASHED_EMAIL_SLUG . "', np: \"woocommerce\" });\n  pintrk('page');\n</script>\n\n<noscript>\n  <img height=\"1\" width=\"1\" style=\"display:none;\" alt=\"\" src=\"https://ct.pinterest.com/v3/?tid=" . self::TAG_ID_SLUG . '&pd[em]=' . self::HASHED_EMAIL_SLUG . "&noscript=1\" />\n</noscript>\n";
+	private static $noscript_base_tag = "<!-- Pinterest Pixel Base Code -->\n<noscript>\n  <img height=\"1\" width=\"1\" style=\"display:none;\" alt=\"\" src=\"https://ct.pinterest.com/v3/?tid=" . self::TAG_ID_SLUG . "&noscript=1\" />\n</noscript>\n<!-- End Pinterest Pixel Base Code -->\n";
```
Comment (JPry) [inline src/Tracking.php]: Since we're not putting any variables in the string, we should use single quotes so that all the double quotes don't need to be escaped.

```suggestion
	private static $noscript_base_tag = '<!-- Pinterest Pixel Base Code -->\n<noscript>\n  <img height="1" width="1" style="display:none;" alt="" src="https://ct.pinterest.com/v3/?tid=' . self::TAG_ID_SLUG . '&noscript=1" />' . "\n</noscript>\n<!-- End Pinterest Pixel Base Code -->\n";
```

File: src/Tracking.php [hunk 2]
```diff
@@ -509,6 +521,21 @@ public static function print_script() {
...
+	 *
+	 * @return void
+	 */
+	public static function print_noscript() {
+
+		if ( ! self::get_active_tag() ) {
+			return;
+		}
+
+		echo self::$noscript_base_tag; //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped --- Printing hardcoded JS tracking code.
```
Comment (JPry) [inline src/Tracking.php]: This needs a `str_replace()` to handle the placeholder tag.

**Review by JPry — CHANGES_REQUESTED** [review]

**Review by sc-ecolasurdo — APPROVED** [review]
