### PR TITLE
Fix deprecated warning for API permissions

### LINKED ISSUE #416: Deprecated warning for API permissions
### Describe the bug:
I'm getting a lot of the following deprecation warnings in my log file. It shows up whenever a WC REST API request is sent (also any request sent from WC).

```
PHP Deprecated:  woocommerce_rest_api_option_permissions is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in wp-includes/functions.php on line 5701
```

It seems to be coming from the code added in this [commit](https://github.com/woocommerce/pinterest-for-woocommerce/commit/f2a4cec9d02b91fb1c3805cc1c625c95e97395ea) and mentions it's been deprecated since WooCommerce Admin version 3.1 (included since WooCommerce 6.2).

There doesn't seem to be an alternative filter available. But in other extensions we've created a separate route/class to handle options/settings instead of trying to extend the WC Admin endpoint. Which could be something like `wp-json/pinterest/v1/settings`, that way you can have full control over who is allowed to access that endpoint.

### Steps to reproduce:
1. Enable debug logging with WP_DEBUG_LOG
2. View the page Marketing > Pinterest or any WC Admin page in the dashboard
3. See multiple deprecated warnings show up in the log

### LINKED ISSUE #423: Deprecated call in code.
```log
[31-Mar-2022 09:51:29 UTC] PHP Deprecated:  woocommerce_rest_api_option_permissions is <strong>deprecated</strong> since version 3.1.0 with no alternative available. in /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/functions.php on line 5701
[31-Mar-2022 09:51:29 UTC] PHP Stack trace:
[31-Mar-2022 09:51:29 UTC] PHP   1. {main}() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/index.php:0
[31-Mar-2022 09:51:29 UTC] PHP   2. require() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/index.php:17
[31-Mar-2022 09:51:29 UTC] PHP   3. wp() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-blog-header.php:16
[31-Mar-2022 09:51:29 UTC] PHP   4. WP->main() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/functions.php:1310
[31-Mar-2022 09:51:29 UTC] PHP   5. WP->parse_request() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/class-wp.php:758
[31-Mar-2022 09:51:29 UTC] PHP   6. do_action_ref_array() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/class-wp.php:396
[31-Mar-2022 09:51:29 UTC] PHP   7. WP_Hook->do_action() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/plugin.php:522
[31-Mar-2022 09:51:29 UTC] PHP   8. WP_Hook->apply_filters() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/class-wp-hook.php:331
[31-Mar-2022 09:51:29 UTC] PHP   9. rest_api_loaded() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/class-wp-hook.php:307
[31-Mar-2022 09:51:29 UTC] PHP  10. WP_REST_Server->serve_request() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/rest-api.php:386
[31-Mar-2022 09:51:29 UTC] PHP  11. apply_filters() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/rest-api/class-wp-rest-server.php:437
[31-Mar-2022 09:51:29 UTC] PHP  12. WP_Hook->apply_filters() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/plugin.php:189
[31-Mar-2022 09:51:29 UTC] PHP  13. rest_send_allow_header() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/class-wp-hook.php:307
[31-Mar-2022 09:51:29 UTC] PHP  14. Automattic\WooCommerce\Admin\API\Options->get_item_permissions_check() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/rest-api.php:797
[31-Mar-2022 09:51:29 UTC] PHP  15. Automattic\WooCommerce\Admin\API\Options->user_has_permission() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Options.php:79
[31-Mar-2022 09:51:29 UTC] PHP  16. Automattic\WooCommerce\Admin\API\Options->get_option_permissions() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Options.php:96
[31-Mar-2022 09:51:29 UTC] PHP  17. apply_filters_deprecated() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Options.php:136
[31-Mar-2022 09:51:29 UTC] PHP  18. _deprecated_hook() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/plugin.php:662
[31-Mar-2022 09:51:29 UTC] PHP  19. trigger_error() /Users/bartoszbudzanowski/Local Sites/pinterest/app/public/wp-includes/functions.php:5701
```

Looks like https://github.com/woocommerce/pinterest-for-woocommerce/blob/2bcc7e9b72c8ed87228d7a5aecab5058d3bed08f/class-pinterest-for-woocommerce.php#L250

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Changes proposed in this Pull Request:
Closes #416.
Closes #423.

A new endpoint was created to handle the settings of the plugin, in order to avoid extending the `wc-admin` option.

### Detailed test instructions:
1. Enable debug logging with WP_DEBUG_LOG.
2. Visit the settings page and update some option.
3. There should be no deprecated warning on logs.

### Changelog entry

> Add - Route to handle the plugin's settings.

### CODE REVIEW

File: src/API/Options.php [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+	 */
+	public function get_settings() {
+		return array(
+			PINTEREST_FOR_WOOCOMMERCE_OPTION_NAME => Pinterest_For_Woocommerce()::get_settings( true ),
+		);
+	}
+
+
+	/**
+	 * Handle get settings.
```
Comment (ksere) [inline src/API/Options.php]:
```suggestion
	 * Handle set settings.
```

File: src/API/Options.php [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+	 *
+	 * @param WP_REST_Request $request The request.
+	 *
+	 * @return array|WP_Error
```
Comment (ksere) [inline src/API/Options.php:57]: I see only array as a possible return

Comment (ksere) [reply src/API/Options.php:57]: Also can these throw exceptions?

File: src/API/VendorAPI.php [hunk 3]
```diff
@@ -94,6 +120,31 @@ public function register_routes() {
...
+	 *
+	 * @since 1.0.11
+	 */
+	public function register_router_multiple_methods() {
+		$namespace = $this->api_namespace . $this->api_version;
+
+		$route_args = array();
+
+		foreach ( $this->endpoint_callbacks_map as $callback => $method ) {
+			$route_args[] = array(
```
Comment (ksere) [inline src/API/VendorAPI.php]: Maybe we could use `register_router_single_method()` in here and avoid some code duplication?

**Review by ksere — CHANGES_REQUESTED** [review]
Looks good, but as is I don't think it fixes the deprecated warnings.

**Review by ksere — APPROVED** [review]

**Comment by alexiglesias31** [comment]
@jconroy, the PR is ready for review.

File: src/API/Options.php [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+/**
+ * API Options
+ *
+ * @package     Pinterest_For_Woocommerce/API
+ * @version     1.0.0
+ */
+
+namespace Automattic\WooCommerce\Pinterest\API;
+
+use Automattic\WooCommerce\Pinterest\Logger as Logger;
```
Comment (JPry) [inline src/API/Options.php]: This import is unused and can be removed.

File: src/API/Options.php [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+	/**
+	 * Handle set settings.
+	 *
+	 * @param WP_REST_Request $request The request.
+	 *
+	 * @return array|WP_Error
+	 */
+	public function set_settings( WP_REST_Request $request ) {
+		if ( ! $request->has_param( PINTEREST_FOR_WOOCOMMERCE_OPTION_NAME ) || ! is_array( $request->get_param( PINTEREST_FOR_WOOCOMMERCE_OPTION_NAME ) ) ) {
+			return new \WP_Error( \PINTEREST_FOR_WOOCOMMERCE_PREFIX . '_options_error', esc_html__( 'Missing option parameters.', 'pinterest-for-woocommerce' ), array( 'status' => 400 ) );
```
Comment (JPry) [inline src/API/Options.php]: Minor: We should also import the `WP_Error` class at the top of the file so that the leading `\` isn't needed here.

File: src/API/VendorAPI.php [hunk 6]
```diff
@@ -78,22 +92,48 @@ public function get_version() {
...
 
 		register_rest_route(
 			$namespace,
 			'/' . $this->base,
 			array(
 				array(
-					'methods'             => $this->methods,
-					'callback'            => array( $this, $this->endpoint_callback ),
+					'methods'             => empty( $methods ) ? $this->methods : $methods,
+					'callback'            => array( $this, empty( $endpoint_callback ) ? $this->endpoint_callback : $endpoint_callback ),
```
Comment (JPry) [inline src/API/VendorAPI.php]: Minor: Determining the value of `$endpoing_callback` should happen in the initial section of the method, separately from this function call.

File: src/API/VendorAPI.php [hunk 7]
```diff
@@ -78,22 +92,48 @@ public function get_version() {
...
+		}
+	}
 
+	/**
+	 * Register endpoint route with single method
+	 *
+	 * @param string $methods The endpoint's methods.
+	 * @param string $endpoint_callback The endpoint's callback.
+	 *
+	 * @since 1.0.11
```
Comment (JPry) [inline src/API/VendorAPI.php]: We have a find/replace process to add the correct version in these tags at the time of the release, so this should instead be the placeholder of `x.x.x`.

```suggestion
	 * @since x.x.x
```

File: src/API/VendorAPI.php [hunk 8]
```diff
@@ -78,22 +92,48 @@ public function get_version() {
...
 					'permission_callback' => array( $this, 'permissions_check' ),
 				),
 			)
 		);
 	}
 
+	/**
+	 * Register endpoint route with multiple methods
+	 *
+	 * @since 1.0.11
```
Comment (JPry) [inline src/API/VendorAPI.php]:
```suggestion
	 * @since x.x.x
```

File: src/API/VendorAPI.php [hunk 9]
```diff
@@ -54,6 +54,20 @@ class VendorAPI {
 	 */
 	public $endpoint_callback;
 
+	/**
+	 * Specify if the endpoint supports multiple methods
+	 *
+	 * @var bool
+	 */
+	public $supports_multiple_endpoints = false;
```
Comment (JPry) [inline src/API/VendorAPI.php]: This should be `protected`, as we don't need `public` access.

```suggestion
	protected $supports_multiple_endpoints = false;
```

File: src/API/VendorAPI.php [hunk 10]
```diff
@@ -54,6 +54,20 @@ class VendorAPI {
...
+
+	/**
+	 * Map with callbacks for each supported method
+	 *
+	 * @var array
+	 */
+	public $endpoint_callbacks_map = array();
```
Comment (JPry) [inline src/API/VendorAPI.php]: This should be `protected`, as we don't need `public` access.

```suggestion
	protected $endpoint_callbacks_map = array();
```

**Review by JPry — CHANGES_REQUESTED** [review]
I reviewed the PHP portion of these changes. Considering that I'm not as familiar with React, I would feel more comfortable with one of our JavaScript engineers looking at the React portion.

**Comment by alexiglesias31** [comment]
Thank you very much @JPry. Pushed the amends for your CR. Looking forward for the JS review.

**Comment by findingsimple** [comment]
Requested a review from Ventures, one of the team will jump in

**Review by eason9487 — APPROVED** [review]
The JS part looks good to me.

File: src/API/Options.php [hunk 11]
```diff
@@ -0,0 +1,72 @@
...
+	 *
+	 * @return array|WP_Error
+	 */
+	public function set_settings( WP_REST_Request $request ) {
+		if ( ! $request->has_param( PINTEREST_FOR_WOOCOMMERCE_OPTION_NAME ) || ! is_array( $request->get_param( PINTEREST_FOR_WOOCOMMERCE_OPTION_NAME ) ) ) {
+			return new WP_Error( \PINTEREST_FOR_WOOCOMMERCE_PREFIX . '_options_error', esc_html__( 'Missing option parameters.', 'pinterest-for-woocommerce' ), array( 'status' => 400 ) );
+		}
+
+		if ( ! Pinterest_For_Woocommerce()::save_settings( $request->get_param( PINTEREST_FOR_WOOCOMMERCE_OPTION_NAME ) ) ) {
+			return new \WP_Error( \PINTEREST_FOR_WOOCOMMERCE_PREFIX . '_options_error', esc_html__( 'There was an error saving the settings.', 'pinterest-for-woocommerce' ), array( 'status' => 500 ) );
```
Comment (JPry) [inline src/API/Options.php]:
```suggestion
			return new WP_Error( \PINTEREST_FOR_WOOCOMMERCE_PREFIX . '_options_error', esc_html__( 'There was an error saving the settings.', 'pinterest-for-woocommerce' ), array( 'status' => 500 ) );
```

**Review by JPry — APPROVED** [review]
One tiny change needed, but this is otherwise good to go.
