### PR TITLE
Stop tracking on 404 and views other than page or product.

### LINKED ISSUE #945: v5: Page visit CAPI event is sent on some admin pages
### Describe the bug:
We see the following in logs

### Steps to reproduce:

1. Connect a user and visit some admin pages

### Expected behavior:
Page visit and all CAPI events to be sent on only the real website

### Actual behavior:
Conversion events logged on admin pages

### Additional details:
{"data":[{"event_id":"page65f8bbc9c1d0b","event_name":"page_visit","action_source":"web","event_time":1710799817,"event_source_url":"https:\/\/joyfully-chief-kingdom.jurassic.ninja\/wp-content\/uploads\/pinterest-for-woocommerce-fpRZXX.xml","partner_name":"ss-woocommerce","user_data":{"client_ip_address":"109.105.54.197","client_user_agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/121.0.0.0 Safari\/537.36"},"language":"en"}]}
2024-03-18T22:10:18+00:00 Debug Response: 

Body: {"num_events_processed":1,"num_events_received":1,"events":[{"status":"processed","error_message":"","warning_message":""}]}
2024-03-18T22:10:20+00:00 Debug POST Request: https://api.pinterest.com/v5/ad_accounts/549767509140/events

{"data":[{"event_id":"page65f8bbcc9777a","event_name":"page_visit","action_source":"web","event_time":1710799820,"event_source_url":"https:\/\/joyfully-chief-kingdom.jurassic.ninja\/wp-content\/uploads\/pinterest-for-woocommerce-iePdXY.xml","partner_name":"ss-woocommerce","user_data":{"client_ip_address":"162.221.128.165","client_user_agent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/120.0.0.0 Safari\/537.36"},"language":"en"}]}
2024-03-18T22:10:20+00:00 Debug Response: 
Status: 200 OK
Screenshot 2024-03-18 at 3 14 02 PM

### PR DESCRIPTION
**Pull request by budzanowski**
Fixes: #945 

Open a 404 page and notice that page_visit should not be recorded.

### CODE REVIEW

File: src/Tracking.php [hunk 1]
```diff
@@ -81,6 +81,11 @@ public function __construct( array $trackers = array() ) {
 	 * @return void
 	 */
 	public function handle_page_visit() {
+		if ( ! ( is_page() || is_product() ) ) {
```
Comment (ecgan) [inline src/Tracking.php]: This means that we are tracking only in page and product, which means we won't be tracking on blog posts, i.e. we won't know conversion from blog posts (i.e. if users landed on a blog post / news post / promotion post, and then proceed to buy stuff)?

**Review by ecgan — COMMENTED** [review]
One question below.
