### PR TITLE
Handle WC5.9 deprecation 

### LINKED ISSUE #259: Deprecated function log: Onboarding:should_show_task.
### Describe the bug:

In WC5.9 Onboarding:should_show_task() was deprecated. TaskList API should be used instead.

### Steps to reproduce:

1. Install and activate the plugin.
2. Go to Marketing -> Pinterest
3. Error should be in logs or directly on screen depending on logging settings.

image

#### Expected behavior

Menu opens without issues.

#### Actual behavior

Deprecation information.

### PR DESCRIPTION
**Pull request by budzanowski**
Closes #259 

### Changes proposed in this pull request

Fixes WC59 deprecation logs for Onboarding::should_show_tasks().

Deprecation handling is performed through a simple static method of a Compat class. A class method was used instead of a plain file with a function to leverage PSR4 autoloading and namespaces.

### Detailed test instructions

1. Follow steps in #259 and confirm that the deprecation log is gone.

### Changelog entry

> Fix - Use Task List API to detect if we should show Pinterest onboarding tasks.

### CODE REVIEW

File: src/Compat.php [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+
+/**
+ * Helper class with functions that handle WordPress and WooCommerce deprecations.
+ * Using helper class with static methods to help with autoloading.
+ */
+class Compat {
+	/**
+	 * Helper function to check if UI should show tasks.
+	 *
+	 * @since x.x.x
```
Comment (layoutd) [inline src/Compat.php:25]: Personal preference, I guess, but the `since` tag could also go with the `class` doc block. Although, with only one method, it makes sense here too.

**Review by layoutd — APPROVED** [review]
💯  Looks good, works well - removes the deprecation warning in 5.9
