### PR TITLE
Handle Connecting with a Personal account.

### LINKED ISSUE #168: [Suggested P0] Properly handle the case of connecting a personal account without linked business account
### Describe the bug:
Catalog sync and Tags installation can only be configured for Pinterest business accounts. Currently from the pinterest-for-woocommerce plugin registration flow you can connect a non-business (personal) account and that results in an error on merchant creation.

{"error":{"message":"None"},"code":654,"data":null,"message":"You must have a business account to create a merchant.","endpoint_name":"v3_create_pp_merchant","status":"failure"}

### Steps to reproduce:
1. Create a personal Pinterest account on Pinterest.com, keep it as logged in
2. Go through the connection with the plugin
3. You will experience the error above

#### Expected behavior
User needs to either convert to a business account or attach a linked business account before proceeding with registration. There are two types of business accounts: 1) a standalone business account or 2) linked business account, see help article [here](https://help.pinterest.com/en/business/article/get-a-business-account).  Currently WooCommerce registration flow connects from the user's personal account. In general, the WooCommerce account connection should be based on business account, as merchant creation requires a business account and feed registration requires merchant account. 

The ideal UX and ask (here we use):
- If detected a user logs in as a personal account, show a message like "no business account is found", next to it, there will be a button called "create business account"
- The button should show a pop-up UI allowing user to create a linked business account, the URL for the popup is https://www.pinterest.com/business/create-linked-account/?next=https%3A%2F%2Fwww.pinterest.com%2Fbusiness%2Flogin%3Fnext%3D%252Foauth%252F%253Fconsumer_id%253D[client_id]%2526redirect_uri%253D[redirect url]
- Once a LBA account is created, use that user_id as the connected id
- [optional] we can also redirect user to convert the personal account into a business account by following [this link](https://help.pinterest.com/en/business/article/get-a-business-account#section-15096)

#### Actual behavior
Currently the plugin connects with the personal account directly. And {"error":{"message":"None"},"code":654,"data":null,"message":"You must have a business account to create a merchant.","endpoint_name":"v3_create_pp_merchant","status":"failure"} throws

### Additional details:

Following are the API calls to check personal account:

https://api.pinterest.com/v3/users/me/ (response format): response.data.is_partner = false (non-partner account)

https://api.pinterest.com/v3/users/me/businesses/ (response format): response.data[] is empty (no linked business account)

Sample API request and responses

- https://api.pinterest.com/v3/users/me/
`{  "code": 0,  "data": {    "indexed": true,    "has_custom_board_sorting_order": false,    "should_show_creator_bubbles": false,    "group_board_count": 0,    "following_count": 5,    "impressum_url": null,    "location": "",    "pin_thumbnail_urls": [],    "is_employee": false,    "show_impressum": false,    "explicitly_followed_by_me": false,    "pins_done_count": 0,    "last_name": "",    "verified_identity": {},    "is_geo_eligible_for_creator_messaging": false,    "user_following_count": 0,    "user_recommendation_reason": {},    "commerce_module_data": {},    "about": "",    "last_pin_like_time": null,    "blocked_by_me": false,    "profile_discovered_public": null,    "is_partner": false,    "image_large_url": "https://s.pinimg.com/images/user/default_280.png",    "native_pin_count": 0,    "dominant_color_css": "#000000",    "show_discovered_feed": null,    "board_count": 0,    "created_at": "Thu, 12 Aug 2021 16:25:30 +0000",    "type": "user",    "repins_from": [],    "has_published_pins": false,    "image_medium_url": "https://s.pinimg.com/images/user/default_150.png",    "active": true,    "pins": [],    "debug": null,    "partner": null,    "id": "…",    "followed_by_me": false,    "domain_verified": false,    "tag": null,    "domain_url": null,    "is_default_image": true,    "image_xlarge_url": "https://s.pinimg.com/images/user/default_444.png",    "profile_cover_source": null,    "username": "narora1986",    "recommendation_reason": null,    "listed_website_url": null,    "image_small_url": "https://s.pinimg.com/images/user/default_60.png",    "like_count": 0,    "pin_count": 0,    "first_name": "Narora",    "show_creator_profile": false,    "website_url": null,    "is_any_website_verified": false,    "full_name": "Narora",    "dominant_color_rgb": [      0,      0,      0    ],    "last_pin_save_time": null,    "subscribed_to_notifications": true,    "profile_views": -1,    "is_primary_website_verified": false,    "last_login_country": "US",    "is_story_pin_creator": false,    "implicitly_followed_by_me": false,    "recent_pin_images": null,    "verified_domains": [],    "follower_count": 0,    "verified_user_websites": [],    "is_verified_merchant": false,    "canonical_merchant_domain": null,    "businesses": [],    "profile_reach": -1  },  "message": "ok",  "endpoint_name": "v3_get_user_handler",  "status": "success"}`
-https://api.pinterest.com/v3/users/me/businesses/
`{
  "code": 0,
  "data": [
    {
      "id": "…",
      "image_large_url": "https://s.pinimg.com/images/user/default_280.png",
      "first_name": "Testing Business1",
      "image_small_url": "https://s.pinimg.com/images/user/default_60.png",
      "full_name": "Testing Business1",
      "last_name": "",
      "image_xlarge_url": "https://s.pinimg.com/images/user/default_444.png",
      "image_medium_url": "https://s.pinimg.com/images/user/default_150.png"
    }
  ],
  "message": "ok",
  "endpoint_name": "v3_get_linked_business_accounts",
  "status": "success"
}`

### LINKED ISSUE #169: [Suggested P0] Properly handle the case of connecting a personal account with linked business account
### Describe the bug:
Similar to https://github.com/saucal/pinterest-for-woocommerce/issues/168, in this case, a personal account may have a few [linked business accounts](https://help.pinterest.com/en/article/manage-your-linked-business-account), we need to make sure we connect with the business account as Catalog sync and Tags installation can only be configured for Pinterest business accounts. Currently from the pinterest-for-woocommerce plugin registration flow you can connect a non-business (personal) account and that results in an error on merchant creation.

{"error":{"message":"None"},"code":654,"data":null,"message":"You must have a business account to create a merchant.","endpoint_name":"v3_create_pp_merchant","status":"failure"}

### Steps to reproduce:
1. Create a personal Pinterest account on Pinterest.com, keep it as logged in
2. Created a [linked business account](https://help.pinterest.com/en/article/manage-your-linked-business-account)
3. Now log out completely from Pinterest, log in using your personal account.  
4. Go through the connection with the plugin
5. You will experience the error above

#### Expected behavior
Currently WooCommerce registration flow connects from the user's personal account. In general, the WooCommerce account connection should be based on business account, as merchant creation requires a business account and feed registration requires merchant account. 

The ideal UX and ask (here we use):
- If detected a user logs in as a personal account and it has LBA associated, show a list of all LBA accounts, allowing the user to pick one of the LBA account, show a "connect" button or something
- Connect button opens following url in popup https://www.pinterest.com/business/switch-account/?business_id=<selected user id>&next=https%3A%2F%2Fwww.pinterest.com%2Fbusiness%2Flogin%3Fnext%3D%252Foauth%252F%253Fconsumer_id%253D<client id>%2526redirect_uri%253D<<redirect url>>
- Once a LBA account is switched and logged in, use that user_id as the connected id

#### Actual behavior
Currently the plugin connects with the personal account directly. And {"error":{"message":"None"},"code":654,"data":null,"message":"You must have a business account to create a merchant.","endpoint_name":"v3_create_pp_merchant","status":"failure"} throws

### Additional details:

Following are the API calls to check personal account:

https://api.pinterest.com/v3/users/me/ (response format): response.data.is_partner = false (non-partner account)

https://api.pinterest.com/v3/users/me/businesses/ (response format): response.data[] is empty (no linked business account) or not empty (has linked business account)

Sample API request and responses

- https://api.pinterest.com/v3/users/me/
`{  "code": 0,  "data": {    "indexed": true,    "has_custom_board_sorting_order": false,    "should_show_creator_bubbles": false,    "group_board_count": 0,    "following_count": 5,    "impressum_url": null,    "location": "",    "pin_thumbnail_urls": [],    "is_employee": false,    "show_impressum": false,    "explicitly_followed_by_me": false,    "pins_done_count": 0,    "last_name": "",    "verified_identity": {},    "is_geo_eligible_for_creator_messaging": false,    "user_following_count": 0,    "user_recommendation_reason": {},    "commerce_module_data": {},    "about": "",    "last_pin_like_time": null,    "blocked_by_me": false,    "profile_discovered_public": null,    "is_partner": false,    "image_large_url": "https://s.pinimg.com/images/user/default_280.png",    "native_pin_count": 0,    "dominant_color_css": "#000000",    "show_discovered_feed": null,    "board_count": 0,    "created_at": "Thu, 12 Aug 2021 16:25:30 +0000",    "type": "user",    "repins_from": [],    "has_published_pins": false,    "image_medium_url": "https://s.pinimg.com/images/user/default_150.png",    "active": true,    "pins": [],    "debug": null,    "partner": null,    "id": "…",    "followed_by_me": false,    "domain_verified": false,    "tag": null,    "domain_url": null,    "is_default_image": true,    "image_xlarge_url": "https://s.pinimg.com/images/user/default_444.png",    "profile_cover_source": null,    "username": "narora1986",    "recommendation_reason": null,    "listed_website_url": null,    "image_small_url": "https://s.pinimg.com/images/user/default_60.png",    "like_count": 0,    "pin_count": 0,    "first_name": "Narora",    "show_creator_profile": false,    "website_url": null,    "is_any_website_verified": false,    "full_name": "Narora",    "dominant_color_rgb": [      0,      0,      0    ],    "last_pin_save_time": null,    "subscribed_to_notifications": true,    "profile_views": -1,    "is_primary_website_verified": false,    "last_login_country": "US",    "is_story_pin_creator": false,    "implicitly_followed_by_me": false,    "recent_pin_images": null,    "verified_domains": [],    "follower_count": 0,    "verified_user_websites": [],    "is_verified_merchant": false,    "canonical_merchant_domain": null,    "businesses": [],    "profile_reach": -1  },  "message": "ok",  "endpoint_name": "v3_get_user_handler",  "status": "success"}`
-https://api.pinterest.com/v3/users/me/businesses/
`{
  "code": 0,
  "data": [
    {
      "id": "…",
      "image_large_url": "https://s.pinimg.com/images/user/default_280.png",
      "first_name": "Testing Business1",
      "image_small_url": "https://s.pinimg.com/images/user/default_60.png",
      "full_name": "Testing Business1",
      "last_name": "",
      "image_xlarge_url": "https://s.pinimg.com/images/user/default_444.png",
      "image_medium_url": "https://s.pinimg.com/images/user/default_150.png"
    }
  ],
  "message": "ok",
  "endpoint_name": "v3_get_linked_business_accounts",
  "status": "success"
}`

### PR DESCRIPTION
**Pull request by ksere**
Closes #168 
Closes #169

### Changes proposed in this pull request

This PR handles the case where the user connects with a personal account. 

After the user has authenticated with a personal account, there are 2 flows:
1. The user has no Linked business account. In that case they are asked to Create a business account:
image

Clicking the "Create Business Account" button will sent the user to Pinterest to create a linked business account. 
That flow in Pinterest doesn't return the user back to the plugin, so to go around that we are refreshing the Authenticated user's Business accounts on window.focus. 

So after the user navigates back to the plugin's tab, the accounts list should be populated.

2. The user already has Linked business accounts. In that case the accounts list will be presented and the flow from this point on is the same as if a Linked business account was created in flow `#1`.
image

Clicking connect will sent the user to the required middleware URL that will switch to the given business account and then navigate the user once again to the Auth screen, 
image

so that Auth will be completed with the selected business account:
image

### Detailed test instructions

1. Start with a clean plugin installation and a new Pinterest account. 
2. Start the onboarding process and Connect to Pinterest.
3. Verify that the plugin asks you to create a Linked Business account. 
4. Click the button to create one, complete the process in Pinterest and return to plugin. 
5. Verify that you are presented with the list of business accounts. (Should be 1 account at this point).
6. Click "connect", to connect to the selected account. 
7. Verify that on the Authentication screen the Business account is selected. 
8. After returning to the onboarding guide, click the 1st step's label on the top of the screen to navigate to the "Connection" step and verify that you are now connected to a business account.

### CODE REVIEW

File: class-pinterest-for-woocommerce.php [hunk 1]
```diff
@@ -794,6 +849,21 @@ public static function is_connected() {
...
+		 * Checks if connected by checking if we got a token in the db.
+		 *
+		 * @return boolean
+		 */
+		public static function is_business_connected() {
+
+			$account_data = self::get_setting( 'account_data' );
+			$is_partner   = isset( $account_data['is_partner'] ) ? (bool) $account_data['is_partner'] : false;
+
+			return $is_partner && self::is_connected();
```
Comment (msaggiorato) [inline class-pinterest-for-woocommerce.php]: Why not check for is_connected early in the function, and avoid checking for specific account data?

This would save some checks from happening that wouldn't have any impact if we're not connected in the first place.

**Review by msaggiorato — CHANGES_REQUESTED** [review]
Left some comments, overall looks good.

File: class-pinterest-for-woocommerce.php (hunk 1 above)
Comment (ksere) [reply class-pinterest-for-woocommerce.php]: Changed! thanks.

**Review by msaggiorato — APPROVED** [review]

File: class-pinterest-for-woocommerce.php [hunk 2]
```diff
@@ -671,20 +682,64 @@ public static function update_account_data() {
...
+		 *
+		 * @param boolean $force_refresh Wether to refresh the data from the API.
+		 *
+		 * @return array
+		 */
+		public static function get_linked_businesses( $force_refresh = false ) {
+
+			$linked_businesses = Pinterest_For_Woocommerce()::get_data( 'linked_businesses' );
+
+			if ( $force_refresh || is_null( $linked_businesses ) ) {
```
Comment (JPry) [inline class-pinterest-for-woocommerce.php]: Comparing directly to `null` is preferable to using `is_null()`. 
```suggestion
			if ( $force_refresh || null === $linked_businesses ) {
```

File: assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js [hunk 3]
```diff
@@ -0,0 +1,116 @@
...
+	Flex,
+	FlexBlock,
+	FlexItem,
+	SelectControl,
+	__experimentalText as Text, // eslint-disable-line @wordpress/no-unsafe-wp-apis --- _experimentalText unlikely to change/disappear and also used by WC Core
+} from '@wordpress/components';
+
+const BusinessAccountSelection = ( {
+	businessAccounts,
+	setAttemptedCreation,
```
Comment (ecgan) [inline assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js]: `setAttemptedCreation` should be renamed to something like `onAttemptedCreation`. The `on-` prefix is important to indicate that it is a function callback that will be called when users click on the "Create business account" button.

File: assets/source/setup-guide/app/steps/SetupAccount.js [hunk 4]
```diff
@@ -1,117 +1,83 @@
...
+	useEffect( () => {
+		if ( attemptedCreation ) {
+			window.addEventListener( 'focus', fetchBusinesses );
+		}
 
-	const openConfirmationModal = () => {
-		setIsConfirmationModalOpen( true );
-	};
+		return () => window.removeEventListener( 'focus', fetchBusinesses );
+	}, [ fetchBusinesses, attemptedCreation ] );
```
Comment (ecgan) [inline assets/source/setup-guide/app/steps/SetupAccount.js]: I think we don't need the `attemptedCreation` `setAttemptedCreation` `useState`, we can just always run `fetchBusinesses` on window focus. With that, even if the user didn't click on the "Create business account" button and they manually go to Pinterest site to setup the business account in a separate window, then when they come back to this window, we would auto fetch the businesses.

File: assets/source/setup-guide/app/steps/SetupAccount.js [hunk 5]
```diff
@@ -1,117 +1,83 @@
...
-				wcSettings.pinterest_for_woocommerce.apiRoute +
-				'/auth_disconnect',
-			method: 'POST',
-		} );
+			setBusinessAccounts( results );
 
-		if ( ! result.disconnected ) {
+			if ( Object.keys( results ).length > 0 ) {
+				window.removeEventListener( 'focus', fetchBusinesses );
+			}
```
Comment (ecgan) [inline assets/source/setup-guide/app/steps/SetupAccount.js]: So the logic here is about "if there are business accounts, don't call `fetchBusinesses` on window focus". This logic should be put inside the `useEffect`, not here.

File: assets/source/setup-guide/app/steps/SetupAccount.js [hunk 6]
```diff
@@ -1,117 +1,83 @@
...
-							{ __( 'Cancel', 'pinterest-for-woocommerce' ) }
-						</Button>
-					</div>
-				</div>
-			</Modal>
-		);
-	};
+	const fetchBusinesses = useCallback( async () => {
+		try {
+			setBusinessAccounts();
```
Comment (ecgan) [inline assets/source/setup-guide/app/steps/SetupAccount.js:50]: Do we need to clear the business accounts state? I think we don't need this?

File: assets/source/setup-guide/app/steps/SetupAccount.js [hunk 7]
```diff
@@ -1,117 +1,83 @@
...
+		return () => window.removeEventListener( 'focus', fetchBusinesses );
+	}, [ fetchBusinesses, attemptedCreation ] );
 
-	const closeConfirmationModal = () => {
-		setIsConfirmationModalOpen( false );
-	};
+	useEffect( () => {
+		if ( ! isConnected ) {
+			setIsBusinessConnected( isConnected );
+		}
```
Comment (ecgan) [inline assets/source/setup-guide/app/steps/SetupAccount.js]: The logic here is "if `isConnected` is false, set `isBusinessConnected` to false. Suggest to change to the following for easier reading.

```suggestion
		if ( ! isConnected ) {
			setIsBusinessConnected( false );
		}
```

File: assets/source/setup-guide/app/steps/SetupAccount.js [hunk 8]
```diff
@@ -1,117 +1,83 @@
...
+	}, [ isConnected, setIsBusinessConnected ] );
```
Comment (ecgan) [inline assets/source/setup-guide/app/steps/SetupAccount.js]: This whole `useEffect` operates solely on the passed down props `isConnected` and `setIsBusinessConnected`. Suggest to move this up closer to where they are used, i.e. `ConnectionApp` and `WizardApp`.

File: assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js [hunk 9]
```diff
@@ -0,0 +1,116 @@
...
+} ) => {
+	const [ targetBusinessId, setTargetBusinessId ] = useState(
+		undefined !== businessAccounts && businessAccounts.length > 0
```
Comment (ecgan) [inline assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js:20]: If we can ensure that `businessAccounts` is always an array, then we don't need to check for undefined?

File: assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+			? businessAccounts[ 0 ][ 'value' ]
+			: null
+	);
+
+	const handleConnectToBusiness = () => {
+		const newURL = addQueryArgs(
+			decodeEntities(
+				wcSettings.pinterest_for_woocommerce.switchBusinessAccountUrl
+			),
```
Comment (ecgan) [inline assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js]: The `switchBusinessAccountUrl` is a piece of data, we don't need to encode it in server side and decode it in JS here. If we do want to display it in HTML, we can encode it in JS.

File: assets/source/setup-guide/app/components/Account/Connection.js [hunk 11]
```diff
@@ -0,0 +1,203 @@
...
+	return (
+		<>
+			<img
+				src={
+					wcSettings.pinterest_for_woocommerce.pluginUrl +
+					'/assets/images/pinterest-logo.svg'
+				}
+				alt=""
+			/>
+		</>
```
Comment (ecgan) [inline assets/source/setup-guide/app/components/Account/Connection.js]: Remove unneeded nesting.

```suggestion
			<img
				src={
					wcSettings.pinterest_for_woocommerce.pluginUrl +
					'/assets/images/pinterest-logo.svg'
				}
				alt=""
			/>
```

File: assets/source/setup-guide/app/components/Account/Connection.js [hunk 12]
```diff
@@ -0,0 +1,203 @@
...
+
+	const handleDisconnectAccount = async () => {
+		closeConfirmationModal();
+
+		const result = await apiFetch( {
+			path:
+				wcSettings.pinterest_for_woocommerce.apiRoute +
+				'/auth_disconnect',
+			method: 'POST',
+		} );
```
Comment (ecgan) [inline assets/source/setup-guide/app/components/Account/Connection.js]: Missing try/catch block and error handling (e.g. lost network connection) for API call.

File: assets/source/setup-guide/app/components/Account/Connection.js [hunk 13]
```diff
@@ -0,0 +1,203 @@
...
+				)
+			);
+		} else {
+			setIsConnected( false );
+
+			// Force reload WC admin page to initiate the relevant dependencies of the Dashboard page.
+			const path = getNewPath( {}, '/pinterest/landing', {} );
+
+			window.location = new URL(
+				decodeEntities( wcSettings.adminUrl + path )
```
Comment (ecgan) [inline assets/source/setup-guide/app/components/Account/Connection.js]: `adminUrl` is a piece of data, no need to encode and decode.

File: assets/source/setup-guide/app/components/Account/Connection.js [hunk 14]
```diff
@@ -0,0 +1,203 @@
...
+						</Text>
+					</FlexBlock>
+
+					<FlexItem>
+						<Button
+							isSecondary
+							href={ decodeEntities(
+								wcSettings.pinterest_for_woocommerce
+									.serviceLoginUrl
+							) }
```
Comment (ecgan) [inline assets/source/setup-guide/app/components/Account/Connection.js]: No need to encode and decode `serviceLoginUrl`.

**Review by ecgan — CHANGES_REQUESTED** [review]
12 comments here, some of them are repeating the same idea (e.g. the "encode and decode URL"). I think they should be addressed to make things cleaner and easier.

File: assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js (hunk 3 above)
Comment (ecgan) [reply assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js]: Related to https://github.com/woocommerce/pinterest-for-woocommerce/pull/213#discussion_r718815360, this function callback may not be needed anymore.

File: class-pinterest-for-woocommerce.php [hunk 15]
```diff
@@ -671,20 +682,64 @@ public static function update_account_data() {
...
+
+				$account_data       = Pinterest_For_Woocommerce()::get_setting( 'account_data' );
```
Comment (JPry) [inline class-pinterest-for-woocommerce.php]: This whole section within the conditional feels like it would be better as its own separate method, something like `update_linked_businesses()`.

File: class-pinterest-for-woocommerce.php [hunk 16]
```diff
@@ -794,6 +849,25 @@ public static function is_connected() {
...
+		/**
+		 * Checks if connected and on a Business account.
+		 *
+		 * @return boolean
+		 */
+		public static function is_business_connected() {
+
+			if ( ! self::is_connected() ) {
+				return false;
+			}
```
Comment (JPry) [inline class-pinterest-for-woocommerce.php]:
```suggestion
			if ( ! self::is_connected() ) {
				return false;
			}
```

File: class-pinterest-for-woocommerce.php [hunk 17]
```diff
@@ -671,20 +682,64 @@ public static function update_account_data() {
...
+		/**
+		 * Fetches a fresh copy (if needed or explicitly requested), of the authenticated user's Linked business accounts.
+		 *
+		 * @param boolean $force_refresh Wether to refresh the data from the API.
+		 *
+		 * @return array
+		 */
+		public static function get_linked_businesses( $force_refresh = false ) {
+
+			$linked_businesses = Pinterest_For_Woocommerce()::get_data( 'linked_businesses' );
```
Comment (JPry) [inline class-pinterest-for-woocommerce.php]:
```suggestion
			$linked_businesses = Pinterest_For_Woocommerce()::get_data( 'linked_businesses' );
```

File: class-pinterest-for-woocommerce.php [hunk 18]
```diff
@@ -794,6 +849,25 @@ public static function is_connected() {
...
+		public static function is_business_connected() {
+
+			if ( ! self::is_connected() ) {
+				return false;
+			}
+
+			$account_data = self::get_setting( 'account_data' );
+			$is_partner   = isset( $account_data['is_partner'] ) ? (bool) $account_data['is_partner'] : false;
+
+			return $is_partner;
```
Comment (JPry) [inline class-pinterest-for-woocommerce.php]: We don't need the `$is_partner` variable here, and we can also simplify the conditional a bit.

```suggestion

			return (bool) ( $account_data['is_partner'] ?? false );
```

File: includes/admin/class-pinterest-for-woocommerce-admin.php [hunk 19]
```diff
@@ -398,31 +398,55 @@ private function get_component_settings() {
...
+				),
+				'switchBusinessAccountUrl' => esc_url(
+					add_query_arg(
+						array(
+							'page' => 'wc-admin',
+							PINTEREST_FOR_WOOCOMMERCE_PREFIX . '_go_to_switch_account' => '1',
+							'view' => 'wizard',
+						),
+						admin_url( 'admin.php' )
+					)
```
Comment (JPry) [inline includes/admin/class-pinterest-for-woocommerce-admin.php]: For readability, these array values would be better as separate methods that return the appropriate value.

File: includes/admin/class-pinterest-for-woocommerce-admin.php [hunk 20]
```diff
@@ -431,11 +455,22 @@ public function maybe_go_to_service_login_url() {
 				return false;
```
Comment (JPry) [inline includes/admin/class-pinterest-for-woocommerce-admin.php]: I know this line isn't part of the set of changes, but the two `return` statements here are inconsistent. The first one does not return a value, while this one does. Since this method is being modified anyway, this value of `false` should be removed.

File: includes/admin/class-pinterest-for-woocommerce-admin.php [hunk 21]
```diff
@@ -431,11 +455,22 @@ public function maybe_go_to_service_login_url() {
...
 			}
 
-			$view = ! empty( $_REQUEST['view'] ) ? sanitize_key( $_REQUEST['view'] ) : null; // phpcs:ignore WordPress.Security.NonceVerification.Recommended --- not needed
+			$context = 'login';
+
+			// phpcs:disable WordPress.Security.NonceVerification.Recommended --- not needed
```
Comment (JPry) [inline includes/admin/class-pinterest-for-woocommerce-admin.php]: Could you explain why the nonce check is not needed here? Skipping a nonce check should have a very good reason why it is unnecessary, and that should also be documented inline as well.

File: src/API/Base.php [hunk 22]
```diff
@@ -284,6 +284,12 @@ public static function get_account_info() {
 	}
 
 
+	public static function get_linked_businesses() {
```
Comment (JPry) [inline src/API/Base.php:287]: This method is missing a docblock.

File: src/API/Base.php [hunk 23]
```diff
@@ -284,6 +284,12 @@ public static function get_account_info() {
...
+		$response = self::make_request( 'users/me/businesses', 'GET' );
+		return $response;
```
Comment (JPry) [inline src/API/Base.php]: `$response` is unnecessary here.

```suggestion
		return self::make_request( 'users/me/businesses', 'GET' );
```

File: src/API/Businesses.php [hunk 24]
```diff
@@ -0,0 +1,75 @@
...
+ * Endpoint handing Pinterest Linked Business Accounts.
+ */
+class Businesses extends VendorAPI {
+
+	/**
+	 * Initialize class
+	 */
+	public function __construct() {
+
+		$this->base              = 'businesses';
```
Comment (JPry) [inline src/API/Businesses.php]:
```suggestion
		$this->base              = 'businesses';
```

File: src/API/Businesses.php [hunk 25]
```diff
@@ -0,0 +1,75 @@
...
+	/**
+	 * Authenticate request
+	 *
+	 * @since 1.0.0
+	 *
+	 * @param WP_REST_Request $request The request.
+	 *
+	 * @return boolean
+	 */
+	public function permissions_check( WP_REST_Request $request ) {
```
Comment (JPry) [inline src/API/Businesses.php]: This method override is unnecessary as it is identical to the parent method.

File: src/API/Businesses.php [hunk 26]
```diff
@@ -0,0 +1,75 @@
...
+		return current_user_can( 'manage_woocommerce' );
+	}
+
+
+	/**
+	 * Get the Linked Business Accounts assigned to the authorized Pinterest account.
+	 *
+	 * @param WP_REST_Request $request The request.
+	 *
+	 * @return array
```
Comment (JPry) [inline src/API/Businesses.php]:
```suggestion
	 * @return array|WP_Error
```

**Review by JPry — CHANGES_REQUESTED** [review]

**Comment by findingsimple** [comment]
@ksere just assigned you as the author

File: assets/source/setup-guide/app/steps/SetupAccount.js (hunk 6 above)
Comment (ksere) [reply assets/source/setup-guide/app/steps/SetupAccount.js:50]: It allows for the Spinner to show while we are refreshing.

File: assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js (hunk 9 above)
Comment (ksere) [reply assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js:20]: `undefined` state is useful here to signify loading. An empty array is a different state.

File: assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js (hunk 10 above)
Comment (ksere) [reply assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js]: It's `esc_url()` in the backend that encodes that. Imho its better to have that and decode it in the frontend. 
I can remove though if its critical.

File: assets/source/setup-guide/app/components/Account/Connection.js (hunk 13 above)
Comment (ksere) [reply assets/source/setup-guide/app/components/Account/Connection.js]: Discussed [here](https://github.com/woocommerce/pinterest-for-woocommerce/pull/213#discussion_r720090383)

File: assets/source/setup-guide/app/components/Account/Connection.js (hunk 14 above)
Comment (ksere) [reply assets/source/setup-guide/app/components/Account/Connection.js]: Discussed [here](https://github.com/woocommerce/pinterest-for-woocommerce/pull/213#discussion_r720090383)

File: includes/admin/class-pinterest-for-woocommerce-admin.php (hunk 21 above)
Comment (ksere) [reply includes/admin/class-pinterest-for-woocommerce-admin.php]: Thanks for pointing this out. Checks were ommited from early on here but code has evolved. Added a nonce check.

File: src/API/Base.php (hunk 23 above)
Comment (ksere) [reply src/API/Base.php]: Removed here and on all other methods of this file

File: assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js [hunk 27]
```diff
@@ -0,0 +1,108 @@
...
+							) }
+						</Button>
+					</FlexItem>
+				</Flex>
+			) }
+		</CardBody>
+	) : (
+		<CardBody size="large">
+			<Spinner />
+		</CardBody>
```
Comment (ecgan) [inline assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js]: @ksere , thanks for the [comment](https://github.com/woocommerce/pinterest-for-woocommerce/pull/213/files#r720080271) about `undefined` being used to indicate loading state. In relation to that comment, if we can have early return `if` block like the following (instead of long ternary operator spanning over many lines), that would make things easier to read. 

```js
if (businessAccounts === undefined) {
	return (
		<CardBody size="large">
			<Spinner />
		</CardBody>
	)
}

return (
	<CardBody size="large" className="business-connection">
		...
	</CardBody>
)
```

File: assets/source/setup-guide/app/steps/SetupAccount.js [hunk 28]
```diff
@@ -1,117 +1,73 @@
...
-
-	const closeConfirmationModal = () => {
-		setIsConfirmationModalOpen( false );
-	};
+	useEffect( () => {
+		if ( undefined !== businessAccounts && businessAccounts.length > 0 ) {
+			window.removeEventListener( 'focus', fetchBusinesses );
+		} else {
+			window.addEventListener( 'focus', fetchBusinesses );
+		}
```
Comment (ecgan) [inline assets/source/setup-guide/app/steps/SetupAccount.js:43]: We can simplify this to the following: 

```js
// only add the event listener
// when it is not in loading state (businessAccounts is not undefined)
// and there are 0 business accounts.
if ( businessAccounts && businessAccounts.length === 0 ) {
	window.addEventListener( 'focus', fetchBusinesses );
}
```

We don't need to have the `window.removeEventListener` because it is called in the effect cleanup function in line 45.

File: assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js (hunk 10 above)
Comment (ecgan) [reply assets/source/setup-guide/app/components/Account/BusinessAccountSelection.js]: Yeah I noticed the `esc_url()`.

> Imho its better to have that and decode it in the frontend.

But, why? 🤔  This is similar to PR https://github.com/woocommerce/pinterest-for-woocommerce/pull/118#discussion_r682069238. 

It's not at critical level, but I just don't see the need for it.

**Review by ecgan — APPROVED** [review]
Added two comments here to further simplify the code. (Plus, another one up here ☝️  https://github.com/woocommerce/pinterest-for-woocommerce/pull/213#pullrequestreview-769264920; I accidentally clicked "Add single comment" button. 😅  )

Other than that, I think it looks all good.

File: assets/source/setup-guide/app/steps/SetupAccount.js (hunk 28 above)
Comment (ksere) [reply assets/source/setup-guide/app/steps/SetupAccount.js:43]: The thinking there is that once we do have `businessAccounts` stop refreshing on window focus since there is no need.

**Comment by ksere** [comment]
@ecgan about [this](https://github.com/woocommerce/pinterest-for-woocommerce/pull/213#discussion_r720480922), you are right, its already being encoded & decoded [here](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/11a678a3aa76f50c5b101ede97588f49e90b095b/src/Assets/AssetDataRegistry.php#L338). Removed that.

**Comment by ksere** [comment]
Pending review from @JPry to merge 😃

File: class-pinterest-for-woocommerce.php [hunk 29]
```diff
@@ -709,21 +709,10 @@ public static function update_account_data() {
...
-					$linked_businesses = $fetched_businesses['data'];
-				}
-
-				$linked_businesses = $linked_businesses ?? array();
-
-				self::save_data( 'linked_businesses', $linked_businesses );
+			$linked_businesses = ! $force_refresh ? Pinterest_For_Woocommerce()::get_data( 'linked_businesses' ) : null;
 
+			if ( null === $linked_businesses ) {
+				$linked_businesses = self::update_linked_businesses( $linked_businesses );
```
Comment (JPry) [inline class-pinterest-for-woocommerce.php]: This method doesn't require an argument.

```suggestion
				$linked_businesses = self::update_linked_businesses();
```

File: src/API/Base.php [hunk 30]
```diff
@@ -236,9 +236,7 @@ protected static function parse_response( $response ) {
 			throw new \Exception( __( 'Empty body', 'pinterest-for-woocommerce' ), 204 );
 		}
 
-		$body = (array) json_decode( $response['body'] );
-
-		return $body;
+		return (array) json_decode( $response['body'] );
```
Comment (JPry) [inline src/API/Base.php]: Minor: Instead of casting to an array, you can pass the second parameter to `json_decode()` to get an array back.

```suggestion
		return json_decode( $response['body'], true );
```

**Review by JPry — APPROVED** [review]
There are a few minor things I noted, but they aren't blockers. Looks good to me!

File: src/API/Base.php (hunk 30 above)
Comment (ksere) [reply src/API/Base.php]: The end result is not same. This would require more changes as we are expecting objects as members of that array in multiple places.

File: assets/source/setup-guide/app/steps/SetupAccount.js (hunk 28 above)
Comment (ecgan) [reply assets/source/setup-guide/app/steps/SetupAccount.js:43]: Yes, correct. When the `businessAccounts` changes (as per the dependency array in line 46):

1. We will first call the `window.removeEventListener` in the effect cleanup function in line 45, from the "old" effect.
2. The "new" effect will kick in, checks for `businessAccounts.length === 0`, and call `window.addEventListener` conditionally.

Reference example: https://reactjs.org/docs/hooks-effect.html#explanation-why-effects-run-on-each-update (search for the "here is a sequence of subscribe and unsubscribe calls that this component could produce over time" in the page).
