### PR TITLE
Show proper error if merchant is connected to a different platform

### LINKED ISSUE #364: [p2] User cannot be connected to multiple active accounts
### Describe the bug:
A user cannot both register and shopify and Woocommerce. The API will fail. Since connecting the partner to feed and related functions happen after user registration process, there is an error. However that error is not displayed correctly to the user
### Steps to reproduce:

1. Create a new pinterest business account or have an account with no stores connected
2. first goto shopify and create a store and install pinterest app from app store
3. connect the business account to pinterest app in shopify
4. create a shop in woocommerce and install the pinterest plugin. 
5. connect the business account to woo commerce

### Expected behavior:
A clear error message is shown to user either during registration or in the setup screen when the error happens during feed process

### Actual behavior:
No error message shown

### Additional details:
Screen Shot 2022-02-10 at 9 56 40 AM

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Changes proposed in this Pull Request:

Closes #364.

This PR adds a proper error when the merchant is connected to a different e-commerce platform (like Shopify).

### Screenshots:

image

### Detailed test instructions:
1. Create a new Pinterest business account or have an account with no stores connected.
2. Go to Shopify, create a store, install Pinterest app and connect your business account.
3. Create a store in WooCommerce, install the plugin and connect your business account.
4. A clear error should be prompted as shows the attached picture.

### Changelog entry

> Add - Clear error when the merchant is connected to another e-commerce platform.

### CODE REVIEW

**Review by ksere — APPROVED** [review]
Ideally we shouldn't save this error status to the database but I don't see any other viable approach without adding more load (outgoing remote requests) to the health check endpoint.

File: src/ProductSync.php [hunk 1]
```diff
@@ -278,6 +278,11 @@ public static function handle_feed_registration() {
 			throw new Exception( esc_html__( 'Could not register feed.', 'pinterest-for-woocommerce' ) );
 
 		} catch ( Throwable $th ) {
+			if ( 4163 === $th->get_pinterest_code() ) {
```
Comment (adarshakb) [inline src/ProductSync.php]: We are handling this error, what if other errors happen in partner connect call?

Comment (alexiglesias31) [reply src/ProductSync.php]: Indeed, we are capturing this specific error.
If there is a well-defined list with the possible errors for this kind of scenario, we could add an error codes map.
However, that is something that should be tackled as an enhancement imho.

**Comment by alexiglesias31** [comment]
@jconroy this PR is ready for CR

File: src/Merchants.php [hunk 2]
```diff
@@ -148,6 +148,9 @@ public static function update_or_create_merchant() {
 			throw new Exception( __( 'Response error when trying create a merchant or update the existing one.', 'pinterest-for-woocommerce' ), 400 );
 		}
 
+		// Clean merchants error code.
+		Pinterest_For_Woocommerce()::save_data( 'merchant_connected_diff_platform', false );
```
Comment (budzanowski) [inline src/Merchants.php]: I would remove it from here and add it to the handle_feed_registration. This way it is always cleared and only set if we get to this particular 4163 code.

First of all, we would have handled `merchant_connected_diff_platform` around the same place, thus easier to maintain. Second, it would always get cleared meaning that if the user setup would be triggering another type of error ( for whatever reason ) we would have only one error to focus on.

Comment (alexiglesias31) [reply src/Merchants.php]: @budzanowski, good point. Done.

**Review by budzanowski — APPROVED** [review]

**Comment by budzanowski** [comment]
:shipit:
