### PR TITLE
Use stored feed profile ID to retrieve catalog status and issues

### LINKED ISSUE #183: Code should check status of the actually generated feed, not the most recent one.
### Describe the bug:
Feed issues are fetched by merchant id, not filtering the feed profile (stored in the database). This can cause inconsistencies.

### Steps to reproduce:
Given a merchant with more than one ingestion feed profile, the feed ingestion status might not be the real status.

#### Expected behavior
Feed status matches the information (or a summarized version of it) to the one displayed in Pinterest.

#### Actual behavior
Inconsistent behaviour in the case of multiple ingestion feed profiles.

### LINKED ISSUE #193: [Related 183?] "Remote sync status" shows incorrect info based on wrong feed from old site
### Describe the bug:

Version tested: https://github.com/woocommerce/pinterest-for-woocommerce/releases/tag/1.0.0-beta.2

I have an existing site connected to an existing Pinterest account. I setup a brand new site with a new URL domain, went through the setup onboarding flow successfully, connected to the same existing Pinterest account, using the same advertiser and tracking tag.

When the setup onboarding is complete, I go to the Catalog tab, this is what I see:

image

It says "XML Feed: Successfully generated 56 mins ago". However, in "Remote sync status", it says "last pulled: 2 hours ago", which does not make sense - how can it pull the feed when the feed was not generated yet?

Also, when I go to Pinterest Catalogs page, I see this:

image

image

In the feed for the new site, the status is "pending", which means Pinterest hasn't pulled the feed from the new site yet. When I expand the old site info, and hover my mouse over the "Date" field, the tooltip shows the exact date and time, which roughly corresponds to the "2 hours ago" stated in "Remote sync status".

I suspect that the "Remote sync status" is getting wrong info from the old feed. It should be getting the info from the new feed.

### Steps to reproduce:

Pre-condition: Have an existing website connected to an existing Pinterest account.

1. Setup a new website with new URL.
2. Go through setup onboarding, connect to existing Pinterest account, use the same advertiser and tracking tag.
3. Go to Catalog page: /wp-admin/admin.php?page=wc-admin&path=%2Fpinterest%2Fcatalog and look at the "remote sync status" field.
4. Go to [Pinterest Catalogs page](https://www.pinterest.com/product-catalogs/data-source/) and check the status of the feed for the new site and old site.

#### Expected behavior

The "remote sync status" should match the feed status for the new site in Pinterest.

#### Actual behavior

The "remote sync status" seems to be getting the feed status for the old site, not the new site.

### Additional details:

Note that this issue is quite time sensitive - you should check the Pinterest Catalog page as soon as the feed registration is done, and periodically refresh the plugin catalog page and Pinterest Catalog page.

### LINKED ISSUE #197: [Related 183?] Issues section is missing with error in API calls after connecting new site to existing Pinterest account
### Describe the bug:

Version tested: https://github.com/woocommerce/pinterest-for-woocommerce/releases/tag/1.0.0-beta.2.

This is possibly related to https://github.com/woocommerce/pinterest-for-woocommerce/issues/193.

I have an existing site connected to an existing Pinterest account. I setup a brand new site with a new URL domain, went through the setup onboarding flow successfully, connected to the same existing Pinterest account, using the same advertiser and tracking tag.

In the Catalog tab, this is what I see:

image

In the Overview section, I have 48 warnings. There is supposed to be an Issues table below, but it is missing. 

When I look into network panel in dev tools, I see this: 

image

The `GET /wp-json/pinterest/v1/feed_issues?paged=1&per_page=25&_locale=user` returns HTTP status 200 OK, and in the response body, there is a `message: "Could not get current feed&#039;s issues. [Call to a member function get_parent_id() on bool]"`. There isn't any related message in the UI.

When I go [Pinterest Catalog page](https://www.pinterest.com/product-catalogs/data-source/) and view the product feed issues for my new site, there are 48 issues (though note that my old site also has 48 issues): 

image

So there are a few issues here: 

- In the `GET /wp-json/pinterest/v1/feed_issues?paged=1&per_page=25&_locale=user` request, if there is a Pinterest API error, then the response should return HTTP error code, not HTTP status 200 OK. Subsequently, the UI should display a related error message. 
- Why does the request not returning the list of issues? I suspect this is because I am connecting a new site to an existing Pinterest account. My Pinterest account has more than one data source in the Catalogs.

### Steps to reproduce:

Pre-condition: Have an existing website connected to an existing Pinterest account.

1. Setup a new website with new URL.
2. Go through setup onboarding, connect to existing Pinterest account, use the same advertiser and tracking tag.
3. Go to Catalog page: /wp-admin/admin.php?page=wc-admin&path=%2Fpinterest%2Fcatalog, wait for the sync to be done, and look at the Overview section. There should be a number of warnings. 
4. Go to the [Pinterest Catalog page](https://www.pinterest.com/product-catalogs/data-source/), find the data source for the new site, click the expand button and click on View issues for the most recent date. The number of issues should match the number you see in Step 3. 

#### Expected behavior

There should be an Issues section below the Overview section. 

#### Actual behavior

The Issues section is missing.

### PR DESCRIPTION
**Pull request by nima-karimi**
Closes #183 

### Changes proposed in this pull request

This PR modifies the calls made to the catalog feed report API to include the stored feed profile ID instead of fetching the report for the last generated feed.

It resolves an issue where if the user has two or more ingestion feed profiles registered in their merchant account, we erroneously displayed the issues and status of an irrelevant feed profile in the app instead of the one that's generated by the plugin for the user's store.

I've also renamed the `ProductSync::is_feed_registered` to `ProductSync::get_registered_feed_id` and fixed the doc block because it doesn't return a boolean at all times and its main purpose seems to be to return the registered feed ID.

### Detailed test instructions

1. Make sure you have at least two ingestion feed profiles registered in your merchant account. You can connect two test stores to your Pinterest merchant account.
2. Check `Marketing > Pinterest > Catalog` and make sure it displays the correct number of Active, Not Synced, Warnings, etc. for your store and also confirm that the product issues are displayed correctly for your products.

### CODE REVIEW

**Comment by findingsimple** [comment]
Can #197 and #193 also be checked to see if they are resolved with this change

File: src/API/Base.php [hunk 1]
```diff
@@ -455,32 +455,23 @@ public static function update_merchant_feed( $merchant_id, $feed_id, $args ) {
...
 	public static function get_merchant_feed( $merchant_id, $feed_id ) {
-		$args = array( 'feed_profile' => $feed_id );
-
 		return self::make_request(
-			add_query_arg( $args, 'catalogs/datasource/feed_report/' . $merchant_id . '/' ),
-			'GET'
+			'catalogs/datasource/feed_report/' . $merchant_id . '/',
+			'GET',
+			array(
+				'feed_profile' => $feed_id
```
Comment (JPry) [inline src/API/Base.php]: Minor: This needs a comma at the end.

```suggestion
				'feed_profile' => $feed_id,
```

**Comment by JPry** [comment]
I started reviewing this today but ran out of time. I'll finish the review in the morning on Wednesday.

File: src/API/Base.php [hunk 2]
```diff
@@ -455,32 +455,23 @@ public static function update_merchant_feed( $merchant_id, $feed_id, $args ) {
...
 	 *
 	 * @return mixed
 	 */
 	public static function get_merchant_feed( $merchant_id, $feed_id ) {
-		$args = array( 'feed_profile' => $feed_id );
-
 		return self::make_request(
-			add_query_arg( $args, 'catalogs/datasource/feed_report/' . $merchant_id . '/' ),
-			'GET'
+			'catalogs/datasource/feed_report/' . $merchant_id . '/',
```
Comment (JPry) [inline src/API/Base.php]: Minor: Let's use interpolation instead of concatenation here.

```suggestion
			"catalogs/datasource/feed_report/{$merchant_id}/",
```

**Review by JPry — APPROVED** [review]
LGTM 👍🏻 Just a couple minor things to tweak, but nothing blocking.
