### PR TITLE
Sync enhanced match support with Pinterest

### LINKED ISSUE #429: Enhanced match value isn't set in the API call to create the tag
### Describe the bug:
When creating a tag, the aem_enabled isnt set to true

There is also options for Name, gender, Location and phone enhanced match apart from email.

Depending on the implementation of the plugin please enable this value appropriately

### Steps to reproduce:

1. Create a new pinterest account (i.e any account which has 0 tags)
2. Connect the account using the plugin
3. Visit the store to generate any tag event
4. Goto pinterest page. Ads->Conversation ... Look at UI. Enhanced match is disabled.

### Expected behavior:
Enhanced match value to be synced with pinterest.

### Actual behavior:
https://github.com/woocommerce/pinterest-for-woocommerce/blob/c257b9c0ce3e3d0939da105d785b304dd067e7c0/src/API/Base.php#L413

### Additional details:

API - https://developers.pinterest.com/docs/redoc/adtech_ads_v4/#operation/create_conversion_tag_handler

Screen Shot 2022-04-01 at 3 45 57 PM
Screen Shot 2022-04-01 at 3 45 24 PM

### LINKED ISSUE #430: Enhanced match value isn't synced with pinterest
### Describe the bug:

This is a continuation of https://github.com/woocommerce/pinterest-for-woocommerce/issues/429 so please refer there for more details

In settings page if enhanced match is disabled and customer enables it, then we need to update the enhanced match value via API PATCH call

API - https://developers.pinterest.com/docs/redoc/adtech_ads_v4/#operation/create_conversion_tag_handler

### Steps to reproduce:

1. Have a pinterest account connect with woo commerce plugin
2. Goto pinterest Ads -> conversion and disable enhanced match
3. In plugin disable enhanced match
4. Now re-enable enchanged match in the plugin.

### Expected behavior:
 It should be enabled automatically in Pinterest when user enables it in the woocommerce site.

### Actual behavior:
No change on pinterest side

### Additional details:

NOTE: Lets hold off on the otherway round of update. i.e when we disable enhanced match on the plugin DONOT disable the enhanced match at pinterest side (only stop sending EM signals from plugin) because the user might have the same tag installed in other places

### PR DESCRIPTION
**Pull request by alexiglesias31**
### Changes proposed in this Pull Request:

Closes #429
Closes #430 

This PR enables the enhanced match setting and syncs this through the Pinterest API.
It covers the following points:

- Set `aem_enabled` when creating a tag.
- For all users that are updating to 1.0.11 we will update the tag with the same value than the setting.
- When the settings are updated trigger a tag update to sync the option with Pinterest.

### Screenshots:

image

#### Creating a new tag
1. Create a new Pinterest account or get an account which has 0 tags.
2. Connect the account using the plugin.
3. Visit the store to generate any tag event.
4. On Pinterest page -> Ads -> Conversions, Automatic enhanced match should be enabled.

#### Update routine
1. On Pinterest page -> Ads -> Conversions disable/enable the Automatic enhanced match (to make it different than the plugin settings).
2. Temporarily bump the value PINTEREST_FOR_WOOCOMMERCE_VERSION in the main plugin file to 1.0.11.
3. Refresh any admin page.
4. On Pinterest page -> Ads -> Conversions, Automatic enhanced match should be synched with the plugin.

#### Enable/Disable in settings
2. On the Pinterest plugin > Settings page enable/disable the enhanced match and save the settings.
3. On Pinterest page -> Ads -> Conversions, Automatic enhanced match should be synched with the plugin.

### CODE REVIEW

File: src/PluginUpdate.php [hunk 1]
```diff
@@ -266,4 +267,35 @@ protected function feed_generation_migration(): void {
...
+			// Already up to date.
+			return;
+		}
+
+		$aem_enabled  = (bool) Pinterest_For_Woocommerce()::get_setting( 'enhanced_match_support', null );
+		$tracking_tag = Pinterest_For_Woocommerce()::get_setting( 'tracking_tag', null );
+
+		// Only update if the setting is enabled and we have a connected tag.
+		if ( ! $aem_enabled || ! $tracking_tag ) {
+			return;
```
Comment (adarshakb) [inline src/PluginUpdate.php:287]: I just left a comment here https://github.com/woocommerce/pinterest-for-woocommerce/issues/430#issuecomment-1090354591

Let me know if its possible to update code.

Hopefully it shouldnt change your logic much.

**Comment by adarshakb** [comment]
could you please also update the help text that comes up next to this settings to tell the user that this is kept in sync with pinterest

**Comment by alexiglesias31** [comment]
@jconroy, @JPry, @mikkamp.
The PR is ready for review.

**Comment by adarshakb** [comment]
Concern

    I see this setting is saved in the plugin. This might cause an error in edgecase where if the user disables the enhanced match (EM) setting in pinterest, when they come to settings page it shows as enabled.
   
    If EM is disabled on pinterest and tag sends EM signals to pinterest, pinterest just ignores them.
    
    So I think we could re-sync the settings value whenever someone loads the plugin page (and/or during the feed sync every 24hours)
    
    We can think through this change, should be not an immediate concern for GTM. 

Please create an issue if my above concern is valid,

otherwise ignore :)

File: class-pinterest-for-woocommerce.php [hunk 2]
```diff
@@ -712,6 +725,54 @@ public static function maybe_disconnect_advertiser( $old_value, $new_value ) {
...
+		private static function maybe_sync_enhanced_match_support( $old_value, $new_value ) {
+
+			if (
+				! isset( $old_value['enhanced_match_support'] ) ||
+				! isset( $new_value['enhanced_match_support'] )
+			) {
+				return;
+			}
+
+			$tracking_tag = self::get_setting( 'tracking_tag', null );
```
Comment (JPry) [inline class-pinterest-for-woocommerce.php]: Minor: the second parameter here is unnecessary

```suggestion
			$tracking_tag = self::get_setting( 'tracking_tag' );
```

File: class-pinterest-for-woocommerce.php [hunk 3]
```diff
@@ -712,6 +725,54 @@ public static function maybe_disconnect_advertiser( $old_value, $new_value ) {
...
+		 *
+		 * @param array $old_value The old value of the option.
+		 * @param array $new_value The new value of the option.
+		 */
+		private static function maybe_sync_enhanced_match_support( $old_value, $new_value ) {
+
+			if (
+				! isset( $old_value['enhanced_match_support'] ) ||
+				! isset( $new_value['enhanced_match_support'] )
+			) {
```
Comment (JPry) [inline class-pinterest-for-woocommerce.php]: This could be combined into a single call to `isset()`:

```suggestion
			if ( ! isset( $old_value['enhanced_match_support'], $new_value['enhanced_match_support'] ) ) {
```

File: class-pinterest-for-woocommerce.php [hunk 4]
```diff
@@ -712,6 +725,54 @@ public static function maybe_disconnect_advertiser( $old_value, $new_value ) {
...
+			if ( $old_value['enhanced_match_support'] !== $new_value['enhanced_match_support'] ) {
+				self::update_tag_config( $tracking_tag, $new_value['enhanced_match_support'] );
+			}
+		}
+
+		/**
+		 * Update the tag on Pinterest.
+		 *
+		 * @param string  $tracking_tag The connected tag.
+		 * @param boolean $enhanced_match_support The value of the enhanced_math_support option.
```
Comment (JPry) [inline class-pinterest-for-woocommerce.php]:
```suggestion
		 * @param bool $enhanced_match_support The value of the enhanced_math_support option.
```

File: class-pinterest-for-woocommerce.php [hunk 5]
```diff
@@ -712,6 +725,54 @@ public static function maybe_disconnect_advertiser( $old_value, $new_value ) {
...
+				Pinterest\API\Base::update_tag(
+					$tracking_tag,
+					array(
+						'aem_enabled' => $enhanced_match_support,
+					)
+				);
+
+			} catch ( \Exception $th ) {
+
+				Pinterest\Logger::log( esc_html__( 'There was an error updating the tag parameters.', 'pinterest-for-woocommerce' ) );
```
Comment (JPry) [inline class-pinterest-for-woocommerce.php]: Do we want to include the exception message in the log?

File: class-pinterest-for-woocommerce.php [hunk 6]
```diff
@@ -712,6 +725,54 @@ public static function maybe_disconnect_advertiser( $old_value, $new_value ) {
...
+		public static function update_tag_config( $tracking_tag, $enhanced_match_support ) {
+			try {
+				Pinterest\API\Base::update_tag(
+					$tracking_tag,
+					array(
+						'aem_enabled' => $enhanced_match_support,
+					)
+				);
+
+			} catch ( \Exception $th ) {
```
Comment (JPry) [inline class-pinterest-for-woocommerce.php]: Minor: Variable name should `$e` for Exception, or `$th` for Throwable.

```suggestion
			} catch ( \Exception $e ) {
```

File: src/PluginUpdate.php [hunk 7]
```diff
@@ -266,4 +267,26 @@ protected function feed_generation_migration(): void {
...
+	 * @return void
+	 */
+	protected function enable_enhanced_match(): void {
+		if ( ! $this->version_needs_update( '1.0.11' ) ) {
+			// Already up to date.
+			return;
+		}
+
+		$aem_enabled  = (bool) Pinterest_For_Woocommerce()::get_setting( 'enhanced_match_support', null );
+		$tracking_tag = Pinterest_For_Woocommerce()::get_setting( 'tracking_tag', null );
```
Comment (JPry) [inline src/PluginUpdate.php]: Both of these don't require the second parameter.

```suggestion
		$aem_enabled  = (bool) Pinterest_For_Woocommerce()::get_setting( 'enhanced_match_support' );
		$tracking_tag = Pinterest_For_Woocommerce()::get_setting( 'tracking_tag' );
```

**Review by JPry — CHANGES_REQUESTED** [review]

File: class-pinterest-for-woocommerce.php [hunk 8]
```diff
@@ -712,6 +725,54 @@ public static function maybe_disconnect_advertiser( $old_value, $new_value ) {
...
+		 * Sync the Enhanced Match Support setting with Pinterest.
+		 *
+		 * @param array $old_value The old value of the option.
+		 * @param array $new_value The new value of the option.
+		 */
+		private static function maybe_sync_enhanced_match_support( $old_value, $new_value ) {
+
+			if (
+				! isset( $old_value['enhanced_match_support'], $new_value['enhanced_match_support'] )
+			) {
```
Comment (JPry) [inline class-pinterest-for-woocommerce.php]: One minor thing: With only one statement, this should now be on a single line.

```suggestion
			if ( ! isset( $old_value['enhanced_match_support'], $new_value['enhanced_match_support'] ) ) {
```

**Review by JPry — APPROVED** [review]
Just a small tweak needed, but this looks good otherwise. I also was able to see the setting change on the Pinterest site after enabling it on my test site.

**Comment by alexiglesias31** [comment]
Thank you for the revision @JPry. Fixed your comment and merging now.
